# Generated by Django 4.2.20 on 2025-05-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuserstudent',
            name='last_date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
