# Generated by Django 4.2.20 on 2025-05-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_whatsappuserstudent_last_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code_upc',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
